## NumPy Array

In [14]:
import numpy as np

In [15]:
mylist = [1, 2, 3]

In [16]:
type(mylist)

list

In [17]:
np.array(mylist)

array([1, 2, 3])

In [18]:
mylist

[1, 2, 3]

In [19]:
myarr = np.array(mylist)

In [20]:
type(myarr)

numpy.ndarray

In [21]:
my_matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [22]:
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [23]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
np.arange(0, 101, 2)

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [30]:
np.zeros(5)

TypeError: Cannot interpret '5' as a data type

In [32]:
np.zeros((2, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [33]:
np.ones((4, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [41]:
len(np.linspace(0, 5, 21))

21

In [43]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [51]:
np.random.rand(5, 2)

array([[0.98830342, 0.0365194 ],
       [0.31164218, 0.88910843],
       [0.47752297, 0.5498009 ],
       [0.97135631, 0.08802828],
       [0.91594563, 0.56583141]])

In [54]:
np.random.randn(10)

array([ 1.09694898, -0.24827589,  0.08018749, -0.7857619 , -0.19668336,
        2.39065283, -0.98776693,  1.20463204,  1.1247576 ,  0.94833305])

In [56]:
np.random.randn(2, 3)

array([[ 1.97263717,  0.46731897, -1.32992736],
       [ 1.00392518, -1.27682163, -0.43589655]])

In [64]:
np.random.randint(0, 101, (4, 5))

array([[24, 13, 42,  7, 30],
       [63, 41, 23, 25, 23],
       [14, 92, 51, 28, 96],
       [79, 18, 39, 31, 99]])

In [67]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [68]:
arr = np.arange(0, 25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [69]:
arr.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [70]:
ranarr = np.random.randint(0, 101, 10)

In [71]:
ranarr.max()

99

In [72]:
ranarr.min()

2

In [73]:
ranarr.argmax()

5

In [74]:
ranarr.argmin()

7

In [75]:
ranarr[7]

2

In [76]:
ranarr.dtype

dtype('int32')

In [77]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [78]:
arr.shape

(25,)

In [80]:
arr = arr.reshape(5,5)

In [82]:
arr.shape

(5, 5)

In [84]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])