In [1]:
import numpy as np

In [2]:
arr = np.arange(0, 11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[8]

8

In [7]:
arr[1:5]

array([1, 2, 3, 4])

In [9]:
arr[:5]

array([0, 1, 2, 3, 4])

In [11]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [12]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
arr[0:5] = 100

In [14]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [15]:
arr = np.arange(0, 11)

In [16]:
slice_of_arr = arr[0:5]

In [17]:
slice_of_arr

array([0, 1, 2, 3, 4])

In [18]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
slice_of_arr[:] = 99

In [20]:
slice_of_arr

array([99, 99, 99, 99, 99])

In [21]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [22]:
arr_copy = arr.copy()

In [23]:
arr[:] = 100

In [25]:
arr_copy

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [26]:
arr

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [27]:
arr_2d = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])

In [28]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [29]:
arr_2d.shape

(3, 3)

In [30]:
arr_2d[0]

array([ 5, 10, 15])

In [31]:
arr_2d[2]

array([35, 40, 45])

In [35]:
arr_2d[0, 2]

15

In [45]:
arr_2d[:2, 1:]

array([[10, 15],
       [25, 30]])

In [46]:
arr = np.arange(1, 11)

In [47]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [48]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [49]:
bool_arr = arr > 4

In [50]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [51]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [52]:
arr[arr > 4]

array([ 5,  6,  7,  8,  9, 10])